site_name: Siryon Yönetim
site_description: Resmi Siryonm Yönetim Dökümanı
site_author: none

# Repository
repo_name: Siryoncom
repo_url: https://github.com/siryoncom/
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020-2021 COKLUK

# Configuration
docs_dir: docs
site_dir: site
strict: true



# Plugins
plugins:
  - search
  - awesome-pages

# Social
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/siryoncom/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      provider: 'github'
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      labels:
        {

          'commit': 'Commit',
          'compare': 'Compare',
          'issue': 'Issue',
          'pr': 'Pull Request',
          'mention': 'User',
          'repo': 'Repository'

        }
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
